name: notes_app
description: A note-taking app.

publish_to: 'none'

version: 2.0.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  hive: ^2.0.4
  provider: ^5.0.0
  path_provider: ^2.0.2
  hive_generator: ^1.1.0
  build_runner: ^2.0.6
  uuid: ^3.0.4
  fluttertoast: ^8.0.7
  flutter_launcher_icons: ^0.9.0
  local_auth: ^1.1.6
  flutter_secure_storage: ^4.2.0
  flutter_plugin_android_lifecycle: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: false
  ios: true
  image_path: "assets/icon/icon.png"

flutter:
  uses-material-design: true
